project_id = "ifsckryvwehynahixmro"

[functions.legal-research]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.lead-finder]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.send-lead-email]
verify_jwt = true

[functions.unsubscribe]
verify_jwt = false

[functions.contact-support]
verify_jwt = true

[functions.support-chat]
verify_jwt = true

[functions.faq-ai]
verify_jwt = true
